import { animated } from '@react-spring/web';
import { DocsViewProps } from '../../../../types/springTypes';
import { DocsNavigation } from '../DocsNavigation';
import { AnchorHeading } from '../../utils/AnchorHeading';
import {
	vueBuild,
	vueComponent,
	vueGenerateHead,
	vueHandler,
	vueImports
} from '../../../data/documentation/vueDocsCode';
import {
	h1Style,
	listItemStyle,
	listStyle,
	mainContentStyle,
	paragraphLargeStyle,
	paragraphSpacedStyle,
	sectionStyle,
	strongStyle
} from '../../../styles/docsStyles';
import {
	gradientHeadingStyle,
	heroGradientStyle
} from '../../../styles/gradientStyles';
import { PrismPlus } from '../../utils/PrismPlus';
import { MobileTableOfContents } from '../../utils/MobileTableOfContents';
import { TableOfContents, TocItem } from '../../utils/TableOfContents';

const tocItems: TocItem[] = [
	{ href: '#build-config', label: 'Build Configuration' },
	{ href: '#page-handler', label: 'Page Handler' },
	{ href: '#generate-head', label: 'Generate Head' },
	{ href: '#vue-components', label: 'Components' },
	{ href: '#vue-imports', label: 'Vue Imports' }
];

const VueHeadOptionsList = () => (
	<ul style={{ ...listStyle, marginTop: '1.5rem' }}>
		<li style={listItemStyle}>
			<strong style={strongStyle}>title</strong>: Sets the page title
		</li>
		<li style={listItemStyle}>
			<strong style={strongStyle}>meta</strong>: Array of meta tags with
			name/property and content
		</li>
		<li style={listItemStyle}>
			<strong style={strongStyle}>link</strong>: Array of link elements
			for canonical URLs, icons, etc.
		</li>
	</ul>
);

export const VueOverviewView = ({
	currentPageId,
	onNavigate,
	themeSprings,
	tocOpen,
	onTocToggle,
	isMobileOrTablet
}: DocsViewProps) => {
	const showDesktopToc = !isMobileOrTablet;

	return (
		<div
			style={{
				display: 'flex',
				flex: 1,
				minHeight: 0,
				overflowX: 'hidden',
				overflowY: 'auto',
				position: 'relative'
			}}
		>
			<div style={mainContentStyle(isMobileOrTablet)}>
				<animated.div style={heroGradientStyle(themeSprings)}>
					<h1 id="vue" style={h1Style(isMobileOrTablet)}>
						Vue
					</h1>
					<p style={paragraphLargeStyle}>
						Server-render Vue 3 components with Composition API and
						full TypeScript support.
					</p>
				</animated.div>

				<section style={sectionStyle}>
					<AnchorHeading
						id="build-config"
						level="h2"
						style={gradientHeadingStyle(themeSprings)}
						themeSprings={themeSprings}
					>
						Build Configuration
					</AnchorHeading>
					<p style={paragraphSpacedStyle}>
						Add Vue to your build by specifying the directory
						containing your Vue components:
					</p>
					<PrismPlus
						codeString={vueBuild}
						language="typescript"
						showLineNumbers={true}
						themeSprings={themeSprings}
					/>
				</section>

				<section style={sectionStyle}>
					<AnchorHeading
						id="page-handler"
						level="h2"
						style={gradientHeadingStyle(themeSprings)}
						themeSprings={themeSprings}
					>
						Page Handler
					</AnchorHeading>
					<p style={paragraphSpacedStyle}>
						Use <code>handleVuePageRequest</code> with{' '}
						<code>asset()</code> to get the compiled paths for both
						the page and index files. The fourth parameter is a head
						tag string generated by <code>generateHeadElement</code>
						:
					</p>
					<PrismPlus
						codeString={vueHandler}
						language="typescript"
						showLineNumbers={true}
						themeSprings={themeSprings}
					/>
				</section>

				<section style={sectionStyle}>
					<AnchorHeading
						id="generate-head"
						level="h2"
						style={gradientHeadingStyle(themeSprings)}
						themeSprings={themeSprings}
					>
						Generate Head
					</AnchorHeading>
					<p style={paragraphSpacedStyle}>
						<code>generateHeadElement</code> creates the head tag
						string from a structured object. This provides a
						type-safe way to set titles, meta tags, and link
						elements:
					</p>
					<PrismPlus
						codeString={vueGenerateHead}
						language="typescript"
						showLineNumbers={true}
						themeSprings={themeSprings}
					/>
					<VueHeadOptionsList />
				</section>

				<section style={sectionStyle}>
					<AnchorHeading
						id="vue-components"
						level="h2"
						style={gradientHeadingStyle(themeSprings)}
						themeSprings={themeSprings}
					>
						Components
					</AnchorHeading>
					<p style={paragraphSpacedStyle}>
						Use Vue 3 Single File Components with the Composition
						API. defineProps provides type-safe prop access:
					</p>
					<PrismPlus
						codeString={vueComponent}
						language="vue"
						showLineNumbers={true}
						themeSprings={themeSprings}
					/>
				</section>

				<section style={sectionStyle}>
					<AnchorHeading
						id="vue-imports"
						level="h2"
						style={gradientHeadingStyle(themeSprings)}
						themeSprings={themeSprings}
					>
						Vue Imports
					</AnchorHeading>
					<p style={paragraphSpacedStyle}>
						When using Vue and Svelte in the same project,
						TypeScript may have conflicts between <code>.vue</code>{' '}
						and <code>.svelte</code> file type definitions. Import
						all Vue components in a seperate file and export that
						object to avoid these conflicts.
					</p>
					<PrismPlus
						codeString={vueImports}
						language="typescript"
						showLineNumbers={true}
						themeSprings={themeSprings}
					/>
					<p style={{ ...paragraphSpacedStyle, marginTop: '1.5rem' }}>
						This is only required when both Vue and Svelte are used
						in the same project. If you&apos;re only using Vue, you
						can omit this option.
					</p>
				</section>

				<DocsNavigation
					currentPageId={currentPageId}
					isMobileOrTablet={isMobileOrTablet}
					onNavigate={onNavigate}
					themeSprings={themeSprings}
				/>
			</div>

			{showDesktopToc && (
				<TableOfContents items={tocItems} themeSprings={themeSprings} />
			)}
			{isMobileOrTablet && onTocToggle && (
				<MobileTableOfContents
					isOpen={tocOpen ?? false}
					items={tocItems}
					onToggle={onTocToggle}
					themeSprings={themeSprings}
				/>
			)}
		</div>
	);
};
