// Generated by scripts/generateEcosystemCatalog.ts. Do not edit by hand.

import type { PackageCategory } from '../../../../types/packageDocs';

export type EcosystemSubpackage = {
	description: string;
	name: string;
	private: boolean;
	version: string | null;
};

export type EcosystemProject = {
	category: PackageCategory;
	description: string;
	directory: string;
	kind: 'monorepo' | 'package' | 'repository';
	name: string;
	packageName: string | null;
	private: boolean;
	repository: string | null;
	subpackages: EcosystemSubpackage[];
	version: string | null;
};

export const ecosystemProjects: EcosystemProject[] = [
	{
		category: 'AI',
		description:
			'Production A2A Protocol 1.0 client and server with streaming, durable tasks, push configuration, and Agency enforcement.',
		directory: 'a2a',
		kind: 'package',
		name: 'A2A',
		packageName: '@absolutejs/a2a',
		private: false,
		repository: 'https://github.com/absolutejs/a2a',
		subpackages: [],
		version: '0.3.6'
	},
	{
		category: 'Frontend & UX',
		description:
			'A fullstack meta-framework for building web applications with TypeScript',
		directory: 'absolutejs',
		kind: 'monorepo',
		name: 'AbsoluteJS',
		packageName: '@absolutejs/absolute',
		private: false,
		repository: 'https://github.com/absolutejs/absolutejs',
		subpackages: [
			{
				description:
					'Native optimizations for AbsoluteJS (darwin arm64)',
				name: '@absolutejs/native-darwin-arm64',
				private: false,
				version: '0.19.0-beta.1127'
			},
			{
				description: 'Native optimizations for AbsoluteJS (darwin x64)',
				name: '@absolutejs/native-darwin-x64',
				private: false,
				version: '0.19.0-beta.1127'
			},
			{
				description:
					'Native optimizations for AbsoluteJS (linux arm64)',
				name: '@absolutejs/native-linux-arm64',
				private: false,
				version: '0.19.0-beta.1127'
			},
			{
				description: 'Native optimizations for AbsoluteJS (linux x64)',
				name: '@absolutejs/native-linux-x64',
				private: false,
				version: '0.19.0-beta.1127'
			},
			{
				description:
					'Native optimizations for AbsoluteJS (windows arm64)',
				name: '@absolutejs/native-windows-arm64',
				private: false,
				version: '0.19.0-beta.1127'
			},
			{
				description:
					'Native optimizations for AbsoluteJS (windows x64)',
				name: '@absolutejs/native-windows-x64',
				private: false,
				version: '0.19.0-beta.1127'
			}
		],
		version: '0.19.0-beta.1127'
	},
	{
		category: 'Dev Tools',
		description:
			'VS Code support for AbsoluteJS projects, starting with HTML and HTMX island authoring.',
		directory: 'absolutejs-vscode-extension',
		kind: 'package',
		name: 'AbsoluteJS VS Code Extension',
		packageName: 'absolutejs-vscode',
		private: false,
		repository: 'https://github.com/absolutejs/vscode-extension',
		subpackages: [],
		version: '0.0.9'
	},
	{
		category: 'Auth & Identity',
		description:
			'Framework-neutral roles, capabilities, navigation, and security read models for AbsoluteJS site administration.',
		directory: 'admin',
		kind: 'package',
		name: 'Admin',
		packageName: '@absolutejs/admin',
		private: false,
		repository: 'https://github.com/absolutejs/admin',
		subpackages: [],
		version: '0.2.0'
	},
	{
		category: 'AI',
		description:
			'Provider-agnostic AI agent authorization with policy, approvals, rejections, durable delegation, execution leases, receipts, kill switches, and signed handoffs.',
		directory: 'agency',
		kind: 'package',
		name: 'Agency',
		packageName: '@absolutejs/agency',
		private: false,
		repository: 'https://github.com/absolutejs/agency',
		subpackages: [],
		version: '0.7.4'
	},
	{
		category: 'AI',
		description:
			'The production-grade, provider-neutral agent stack for AbsoluteJS: auth, actions, runtime, sandboxing, trust, memory, inbox, discovery, MCP, A2A, policy, wallet limits, controls, and conformance.',
		directory: 'agent',
		kind: 'package',
		name: 'Agent',
		packageName: '@absolutejs/agent',
		private: false,
		repository: 'https://github.com/absolutejs/agent',
		subpackages: [],
		version: '0.25.0'
	},
	{
		category: 'AI',
		description:
			'Independently published modules for the AbsoluteJS agent stack.',
		directory: 'agent-modules',
		kind: 'monorepo',
		name: 'Agent Modules',
		packageName: '@absolutejs/agent-modules',
		private: true,
		repository: 'https://github.com/absolutejs/agent-modules',
		subpackages: [
			{
				description:
					'Provider-neutral adversarial conformance for agent security plus A2A, MCP, Arazzo, and WebMCP standards.',
				name: '@absolutejs/agent-conformance',
				private: false,
				version: '0.15.1'
			},
			{
				description:
					'Authenticated AI agent operator API, console, and bound plan-then-execute playground.',
				name: '@absolutejs/agent-control',
				private: false,
				version: '0.5.8'
			},
			{
				description:
					'Signed, searchable, provider-neutral AI agent discovery with live schemas and A2A, MCP, Arazzo, and WebMCP interfaces.',
				name: '@absolutejs/agent-discovery',
				private: false,
				version: '0.2.4'
			},
			{
				description:
					'Durable verified webhooks, event subscriptions, schedules, leases, retries, and dead letters for AI agent triggers.',
				name: '@absolutejs/agent-inbox',
				private: false,
				version: '0.3.5'
			},
			{
				description:
					'Scoped durable provenance-aware memory with authorization, retention, erasure, encryption seams, and pluggable retrieval for AI agents.',
				name: '@absolutejs/agent-memory',
				private: false,
				version: '0.1.7'
			},
			{
				description:
					'Evidence-based scoped AI agent reputation with W3C Verifiable Credentials 2.0 adapters.',
				name: '@absolutejs/agent-reputation',
				private: false,
				version: '0.2.3'
			},
			{
				description:
					'Durable provider-neutral AI agent runs, steps, checkpoints, budgets, leases, timers, effects, and handoffs.',
				name: '@absolutejs/agent-runtime',
				private: false,
				version: '0.2.6'
			},
			{
				description:
					'Deny-by-default capability grants and provider-neutral HTTP, filesystem, process, and credential-safe action adapters for AI agents.',
				name: '@absolutejs/agent-sandbox',
				private: false,
				version: '0.2.2'
			},
			{
				description:
					'Provider-neutral provenance, taint propagation, instruction/data separation, and sink policy enforcement for AI agents.',
				name: '@absolutejs/agent-trust',
				private: false,
				version: '0.2.2'
			}
		],
		version: null
	},
	{
		category: 'AI',
		description:
			'The public, signed, searchable registry of AbsoluteJS agents.',
		directory: 'agents',
		kind: 'package',
		name: 'Public Agent Registry',
		packageName: '@absolutejs/public-agent-registry',
		private: true,
		repository: 'https://github.com/absolutejs/agents',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'AI',
		description:
			'Search verified agents and production agent-first AbsoluteJS packages from any MCP client.',
		directory: 'agents-mcp',
		kind: 'package',
		name: 'Agents MCP',
		packageName: '@absolutejs/agents-mcp',
		private: false,
		repository: 'https://github.com/absolutejs/agents-mcp',
		subpackages: [],
		version: '0.2.2'
	},
	{
		category: 'AI',
		description:
			'AI runtime, providers, streaming, and framework adapters extracted from AbsoluteJS',
		directory: 'ai',
		kind: 'package',
		name: 'Ai',
		packageName: '@absolutejs/ai',
		private: false,
		repository: 'https://github.com/absolutejs/ai',
		subpackages: [],
		version: '0.0.47'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Typed, tenant-fenced, privacy-thresholded product and operational analytics primitives for AbsoluteJS.',
		directory: 'analytics',
		kind: 'package',
		name: 'Analytics',
		packageName: '@absolutejs/analytics',
		private: false,
		repository: 'https://github.com/absolutejs/analytics',
		subpackages: [],
		version: '0.1.1'
	},
	{
		category: 'AI',
		description:
			'Arazzo 1.1 workflow discovery, validation, planning, and policy-aware execution for AI agents.',
		directory: 'arazzo',
		kind: 'package',
		name: 'Arazzo',
		packageName: '@absolutejs/arazzo',
		private: false,
		repository: 'https://github.com/absolutejs/arazzo',
		subpackages: [],
		version: '0.1.3'
	},
	{
		category: 'AI',
		description:
			'Typed, versioned artifacts for AI products — schemas, lifecycle, storage, rendering, publishing, revisions, and agent tools without prescribing a database or host.',
		directory: 'artifacts',
		kind: 'package',
		name: 'Artifacts',
		packageName: '@absolutejs/artifacts',
		private: false,
		repository: 'https://github.com/absolutejs/artifacts',
		subpackages: [],
		version: '0.1.3'
	},
	{
		category: 'Platform & Infra',
		description:
			'Keyless Sigstore attestation policy, provenance, signing, and verification for private CI pipelines.',
		directory: 'attest',
		kind: 'package',
		name: 'Attest',
		packageName: '@absolutejs/attest',
		private: false,
		repository: 'https://github.com/absolutejs/attest',
		subpackages: [],
		version: '0.1.3'
	},
	{
		category: 'Commerce & Growth',
		description:
			"In-house audience & affinity intelligence — psychographic inference, interest/brand affinity profiles, and audience-overlap scoring from public signals, provider- and embedding-injected, so you don't pay an audience-intelligence SaaS per seat.",
		directory: 'audience',
		kind: 'package',
		name: 'Audience',
		packageName: '@absolutejs/audience',
		private: false,
		repository: 'https://github.com/absolutejs/audience',
		subpackages: [],
		version: '0.0.4'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Audiense adapter for @absolutejs/audience — implements the AudienceSource contract against the Audiense Insights API (reports, demographics, affinities, influencers, audience overlap). The premium social-graph backfill for AbsoluteJS audience intelligence.',
		directory: 'audience-audiense',
		kind: 'package',
		name: 'Audience Audiense Adapter',
		packageName: '@absolutejs/audience-audiense',
		private: false,
		repository: null,
		subpackages: [],
		version: '0.0.1'
	},
	{
		category: 'Observability',
		description:
			'Cross-surface audit-event substrate for the AbsoluteJS ecosystem — append-only event log with pluggable sinks, optional hash-chain tamper-evidence, and live-wire helpers that thread sync mutations, queue jobs, runtime exits, and secret rotations into one unified log.',
		directory: 'audit',
		kind: 'package',
		name: 'Audit',
		packageName: '@absolutejs/audit',
		private: false,
		repository: 'https://github.com/absolutejs/audit',
		subpackages: [],
		version: '0.2.3'
	},
	{
		category: 'Observability',
		description:
			'Monorepo root for @absolutejs/audit storage adapters. Subpackages live in ./<name>/ and publish independently.',
		directory: 'audit-adapters',
		kind: 'monorepo',
		name: 'Audit Adapters',
		packageName: 'audit-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/audit-adapters',
		subpackages: [
			{
				description:
					'Elysia plugin emitting one structured audit event per request into @absolutejs/audit. Wires into onRequest + onAfterResponse so success AND error paths are captured. Orthogonal to @elysiajs/server-timing (perf headers) and @elysiajs/opentelemetry (sampled tracing); optionally correlates with the active OTel trace id.',
				name: '@absolutejs/audit-elysia',
				private: false,
				version: '0.1.2'
			},
			{
				description:
					'Postgres-backed AuditSink for @absolutejs/audit with first-class Drizzle and tagged-template adapters, native JSONB metadata, and indexed history.',
				name: '@absolutejs/audit-postgres',
				private: false,
				version: '0.1.4'
			},
			{
				description:
					'S3-compatible AuditSink for @absolutejs/audit. Buffered JSONL writes to AWS S3 / Cloudflare R2 / Backblaze B2 / MinIO. Time-sortable object keys; WORM-bucket-friendly for compliance retention.',
				name: '@absolutejs/audit-s3',
				private: false,
				version: '0.1.1'
			}
		],
		version: null
	},
	{
		category: 'Auth & Identity',
		description: 'An authorization library for absolutejs',
		directory: 'auth',
		kind: 'package',
		name: 'Auth',
		packageName: '@absolutejs/auth',
		private: false,
		repository: 'https://github.com/absolutejs/absolute-auth',
		subpackages: [],
		version: '0.59.2'
	},
	{
		category: 'Auth & Identity',
		description:
			'Monorepo root for @absolutejs/auth provider adapters. Subpackages live in ./<name>/ and publish independently.',
		directory: 'auth-adapters',
		kind: 'monorepo',
		name: 'Auth Adapters',
		packageName: 'auth-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/auth-adapters',
		subpackages: [
			{
				description:
					'Twilio Verify provider for @absolutejs/auth MFA challenges.',
				name: '@absolutejs/auth-twilio',
				private: false,
				version: '0.3.0'
			}
		],
		version: null
	},
	{
		category: 'Platform & Infra',
		description:
			'Horizontal-scaling policy substrate for the AbsoluteJS PaaS. createAutoscaler periodically evaluates pluggable signals (CPU, queue depth, latency, ...) against a declarative policy (min/max instances, scale-up/down thresholds, cooldowns) and drives a caller-supplied actuator (spawn / drain / terminate). Pure decision logic — cloud-specific actuators live in the control plane.',
		directory: 'autoscaler',
		kind: 'package',
		name: 'Autoscaler',
		packageName: '@absolutejs/autoscaler',
		private: false,
		repository: 'https://github.com/absolutejs/autoscaler',
		subpackages: [],
		version: '0.2.1'
	},
	{
		category: 'Observability',
		description:
			'Tiny, zero-dependency browser SDK for the AbsoluteJS observability stack. Captures uncaught errors + unhandled rejections, breadcrumbs (console/click/fetch/history), batches, and POSTs an envelope to @absolutejs/errors/ingest via sendBeacon/keepalive. ~2-5KB gz, no Effect in the browser; end-to-end type-safe via the shared erased envelope contract.',
		directory: 'beacon',
		kind: 'package',
		name: 'Beacon',
		packageName: '@absolutejs/beacon',
		private: false,
		repository: 'https://github.com/absolutejs/beacon',
		subpackages: [],
		version: '0.4.4'
	},
	{
		category: 'Dev Tools',
		description:
			'Reproducible performance and accuracy comparisons for AbsoluteJS packages.',
		directory: 'benchmarks',
		kind: 'monorepo',
		name: 'Benchmarks',
		packageName: null,
		private: true,
		repository: 'https://github.com/absolutejs/benchmarks',
		subpackages: [
			{
				description:
					'Head-to-head: @absolutejs/sync vs Zero vs Convex on a shared-counter workload.',
				name: '@absolutejs/sync-benchmarks',
				private: true,
				version: '0.0.0'
			},
			{
				description:
					'Performance & accuracy benchmarks for @absolutejs/voice (STT, TTS, duplex, telephony, sessions) vs. Vapi.',
				name: '@absolutejs/voice-benchmarks',
				private: true,
				version: '0.0.0'
			}
		],
		version: null
	},
	{
		category: 'Platform & Infra',
		description:
			'Cost-model substrate for the AbsoluteJS PaaS. createPlan declares a priced product (base fee + per-dimension unit prices + tiered / free-tier rules); computeInvoice turns a @absolutejs/metering Usage snapshot into Invoice line items in integer micros (no float drift). Pluggable invoice sinks (Stripe / etc.) live in @absolutejs/billing-adapters/*.',
		directory: 'billing',
		kind: 'package',
		name: 'Billing',
		packageName: '@absolutejs/billing',
		private: false,
		repository: 'https://github.com/absolutejs/billing',
		subpackages: [],
		version: '0.6.0'
	},
	{
		category: 'Data & Sync',
		description:
			'Object storage substrate for AbsoluteJS. One BlobStore interface with bounded streaming local and S3-compatible adapters, plus official AWS SDK wiring for multipart object storage.',
		directory: 'blob',
		kind: 'package',
		name: 'Blob',
		packageName: '@absolutejs/blob',
		private: false,
		repository: 'https://github.com/absolutejs/blob',
		subpackages: [],
		version: '0.5.1'
	},
	{
		category: 'Frontend & UX',
		description:
			'Headless, typed blog publishing primitives for AbsoluteJS: post registries, reading metrics, SEO metadata, feeds, sitemap routes, Elysia endpoints, and React hooks without bundled UI.',
		directory: 'blog',
		kind: 'package',
		name: 'Blog',
		packageName: '@absolutejs/blog',
		private: false,
		repository: 'https://github.com/absolutejs/blog',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Auth & Identity',
		description: 'OAuth 2.0 library for TypeScript',
		directory: 'citra',
		kind: 'package',
		name: 'Citra',
		packageName: 'citra',
		private: false,
		repository: 'https://github.com/absolutejs/citra',
		subpackages: [],
		version: '0.29.11'
	},
	{
		category: 'Dev Tools',
		description:
			'Substrate CLI for the AbsoluteJS PaaS — secrets / env / deploy verbs over @absolutejs/secrets, @absolutejs/deploy, and @absolutejs/audit. Config-file driven; sibling to @absolutejs/absolute (the framework CLI).',
		directory: 'cli',
		kind: 'package',
		name: 'Cli',
		packageName: '@absolutejs/cli',
		private: false,
		repository: 'https://github.com/absolutejs/cli',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Deterministic collectible sets, editions, shuffled serials, weighted traits, rarity explanations, and population reports for AbsoluteJS apps.',
		directory: 'collectibles',
		kind: 'package',
		name: 'Collectibles',
		packageName: '@absolutejs/collectibles',
		private: false,
		repository: 'https://github.com/absolutejs/collectibles',
		subpackages: [],
		version: '0.1.2'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Provider-agnostic commerce primitives (cart, orders, fulfillment, shipping) for AbsoluteJS',
		directory: 'commerce',
		kind: 'package',
		name: 'Commerce',
		packageName: '@absolutejs/commerce',
		private: false,
		repository: 'https://github.com/absolutejs/commerce',
		subpackages: [],
		version: '0.40.1-beta.13'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Payment, fulfillment, shipping, and transactional-email adapters for @absolutejs/commerce.',
		directory: 'commerce-adapters',
		kind: 'monorepo',
		name: 'Commerce Adapters',
		packageName: '@absolutejs/commerce-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/commerce-adapters',
		subpackages: [
			{
				description:
					'CustomCat print-on-demand fulfillment adapter for @absolutejs/commerce',
				name: '@absolutejs/commerce-customcat',
				private: false,
				version: '0.6.20-beta.2'
			},
			{
				description:
					'EasyPost shipping adapter for @absolutejs/commerce',
				name: '@absolutejs/commerce-easypost',
				private: false,
				version: '0.19.19-beta.3'
			},
			{
				description:
					'Resend transactional-email adapter for @absolutejs/commerce',
				name: '@absolutejs/commerce-resend',
				private: false,
				version: '0.19.19-beta.3'
			},
			{
				description:
					'Stripe payment + checkout adapter for @absolutejs/commerce',
				name: '@absolutejs/commerce-stripe',
				private: false,
				version: '0.25.1-beta.3'
			}
		],
		version: null
	},
	{
		category: 'Platform & Infra',
		description:
			'Framework-agnostic compliance substrate for the AbsoluteJS PaaS. Declarative data classification + residency + retention policies; orchestrators for retention sweeps, Subject Access Requests, right-to-erasure, and evidence bundles. Composes onto @absolutejs/audit + @absolutejs/telemetry without vendoring any specific framework (SOC2 / HIPAA / ISO 27001 / GDPR).',
		directory: 'compliance',
		kind: 'package',
		name: 'Compliance',
		packageName: '@absolutejs/compliance',
		private: false,
		repository: 'https://github.com/absolutejs/compliance',
		subpackages: [],
		version: '0.7.0'
	},
	{
		category: 'Dev Tools',
		description:
			'Local OpenID Foundation conformance tooling used to validate standards-based identity implementations.',
		directory: 'conformance-suite',
		kind: 'monorepo',
		name: 'OpenID Conformance Suite',
		packageName: null,
		private: true,
		repository: 'https://gitlab.com/openid/conformance-suite',
		subpackages: [
			{
				description: 'No package description provided.',
				name: 'cts-frontend-e2e',
				private: true,
				version: '0.0.1'
			}
		],
		version: null
	},
	{
		category: 'Dev Tools',
		description: 'A CLI tool to create a new AbsoluteJS project',
		directory: 'create-absolutejs',
		kind: 'package',
		name: 'Create AbsoluteJS',
		packageName: 'create-absolutejs',
		private: false,
		repository: 'https://github.com/absolutejs/create-absolutejs',
		subpackages: [],
		version: '0.15.7'
	},
	{
		category: 'Commerce & Growth',
		description: 'Multi-vendor CRM adapter framework for AbsoluteJS',
		directory: 'crm',
		kind: 'package',
		name: 'Crm',
		packageName: '@absolutejs/crm',
		private: false,
		repository: 'https://github.com/absolutejs/crm',
		subpackages: [],
		version: '0.0.10-alpha.10'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Monorepo root for @absolutejs/discover dataset adapters — open-data sources (GLEIF, SEC EDGAR, GitHub, …) normalized to the DatasetSource contract. Subpackages live in ./<name>/ and publish independently as @absolutejs/dataset-<name>.',
		directory: 'dataset-adapters',
		kind: 'monorepo',
		name: 'Dataset Adapters',
		packageName: 'dataset-adapters',
		private: true,
		repository: null,
		subpackages: [
			{
				description:
					"GitHub DatasetSource adapter for @absolutejs/discover — resolve a company's GitHub org and surface its public members (founders/leads, occasionally a public email) for tech-company contact discovery.",
				name: '@absolutejs/dataset-github',
				private: false,
				version: '0.0.2'
			},
			{
				description:
					'GLEIF (Global LEI) DatasetSource adapter for @absolutejs/discover — resolve a company to its official legal entity (LEI, jurisdiction, country) from open CC0 registry data.',
				name: '@absolutejs/dataset-gleif',
				private: false,
				version: '0.0.3'
			},
			{
				description:
					'SEC EDGAR DatasetSource adapter for @absolutejs/discover — resolve a US public company (CIK) and its insiders (officers/directors via Form 3/4/5) from public-domain U.S. government filings.',
				name: '@absolutejs/dataset-sec-edgar',
				private: false,
				version: '0.0.2'
			}
		],
		version: null
	},
	{
		category: 'Dev Tools',
		description:
			'Automated product-demo runtime for AbsoluteJS — drives browser and desktop workflows, records the screen, adds presenter-style highlights, and coordinates AI voiceover.',
		directory: 'demo',
		kind: 'package',
		name: 'Demo',
		packageName: '@absolutejs/demo',
		private: false,
		repository: 'https://github.com/absolutejs/demo',
		subpackages: [],
		version: '0.0.1-beta.0'
	},
	{
		category: 'Platform & Infra',
		description:
			'Generic Bun-project deploy pipeline. A Target (localTarget / sshTarget) is anywhere you can exec + upload — DigitalOcean droplets, Linode, Hetzner, Vultr, your own boxes. Bundled pipeline: prepare → upload → install → build → link → restart → verify. Atomic symlink swap, release history, prune, hooks. SSH shells out to system ssh/rsync — zero ssh2 deps.',
		directory: 'deploy',
		kind: 'package',
		name: 'Deploy',
		packageName: '@absolutejs/deploy',
		private: false,
		repository: 'https://github.com/absolutejs/deploy',
		subpackages: [],
		version: '0.21.0'
	},
	{
		category: 'Commerce & Growth',
		description:
			"In-house B2B decision-maker discovery — find the right person at a company via importable open-data adapters + LLM/web, so you don't pay PDL/Apollo per person-search.",
		directory: 'discover',
		kind: 'package',
		name: 'Discover',
		packageName: '@absolutejs/discover',
		private: false,
		repository: 'https://github.com/absolutejs/discover',
		subpackages: [],
		version: '0.0.9'
	},
	{
		category: 'Messaging',
		description:
			'Provider-agnostic outbound dispatcher for email, carrier and rich messaging, and push notifications in the AbsoluteJS ecosystem.',
		directory: 'dispatch',
		kind: 'package',
		name: 'Dispatch',
		packageName: '@absolutejs/dispatch',
		private: false,
		repository: 'https://github.com/absolutejs/dispatch',
		subpackages: [],
		version: '0.7.1'
	},
	{
		category: 'Messaging',
		description:
			'Monorepo root for @absolutejs/dispatch vendor adapters. Subpackages live in ./<name>/ and publish independently.',
		directory: 'dispatch-adapters',
		kind: 'monorepo',
		name: 'Dispatch Adapters',
		packageName: 'dispatch-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/dispatch-adapters',
		subpackages: [
			{
				description:
					'Apple Push Notification service HTTP/2 PushAdapter for @absolutejs/dispatch with ES256 provider-token rotation.',
				name: '@absolutejs/dispatch-apns',
				private: false,
				version: '0.2.0'
			},
			{
				description:
					'AWS End User Messaging SMS, MMS, RCS, Notify, and WhatsApp adapter for @absolutejs/dispatch.',
				name: '@absolutejs/dispatch-aws-end-user-messaging',
				private: false,
				version: '0.1.0'
			},
			{
				description:
					'Firebase Cloud Messaging HTTP v1 PushAdapter for @absolutejs/dispatch with ADC and short-lived OAuth token support.',
				name: '@absolutejs/dispatch-fcm',
				private: false,
				version: '0.2.0'
			},
			{
				description:
					'Infobip Messages API omnichannel adapter for @absolutejs/dispatch with validation, webhooks, and US registration workflows.',
				name: '@absolutejs/dispatch-infobip',
				private: false,
				version: '0.1.0'
			},
			{
				description:
					"Postmark-backed EmailAdapter for @absolutejs/dispatch. Maps EmailMessage to Postmark's sendEmail params; surfaces the MessageID as DispatchResult.id.",
				name: '@absolutejs/dispatch-postmark',
				private: false,
				version: '0.1.0'
			},
			{
				description:
					'Durable PostgreSQL device registry and fenced fanout claims for @absolutejs/dispatch push lifecycle.',
				name: '@absolutejs/dispatch-push-postgres',
				private: false,
				version: '0.1.0'
			},
			{
				description:
					'Resend-backed EmailAdapter with credential-safe installed effects, signed evidence, and reference-gated query recovery.',
				name: '@absolutejs/dispatch-resend',
				private: false,
				version: '0.7.0'
			},
			{
				description:
					'Production Sinch Conversation API adapter for AbsoluteJS with multichannel fallback, signed durable webhooks, consent, readiness, and 10DLC workflows.',
				name: '@absolutejs/dispatch-sinch',
				private: false,
				version: '0.3.0'
			},
			{
				description:
					'Production Telnyx SMS, MMS, and RCS messaging for @absolutejs/dispatch with signed webhooks, consent-safe scheduling, registration workflows, and readiness checks.',
				name: '@absolutejs/dispatch-telnyx',
				private: false,
				version: '0.3.0'
			},
			{
				description:
					'Production Twilio SMS, MMS, RCS, and WhatsApp for @absolutejs/dispatch with consent enforcement, signed webhooks, registration automation, and readiness checks.',
				name: '@absolutejs/dispatch-twilio',
				private: false,
				version: '0.7.0'
			},
			{
				description:
					'Production Vonage Messages API adapter for AbsoluteJS with multichannel failover, signed durable webhooks, consent, readiness, and 10DLC inspection.',
				name: '@absolutejs/dispatch-vonage',
				private: false,
				version: '0.2.0'
			}
		],
		version: null
	},
	{
		category: 'Dev Tools',
		description:
			'Documentation site for AbsoluteJS and its associated packages (deployed app, not a published library).',
		directory: 'docs',
		kind: 'package',
		name: 'Docs',
		packageName: '@absolutejs/docs',
		private: true,
		repository: 'https://github.com/absolutejs/absolutejs-docs',
		subpackages: [],
		version: '0.0.1'
	},
	{
		category: 'Data & Sync',
		description:
			"Tiny error helpers for @absolutejs Eden Treaty clients. Unwraps Eden's { status, value } failure shape into a real Error that KEEPS the HTTP status, so call sites stop dropping it. Zero dependencies.",
		directory: 'eden',
		kind: 'package',
		name: 'Eden',
		packageName: '@absolutejs/eden',
		private: false,
		repository: null,
		subpackages: [],
		version: '0.2.0'
	},
	{
		category: 'AI',
		description:
			'Deny-by-default outbound network policy and credential-safe fetch for AI agents.',
		directory: 'egress',
		kind: 'package',
		name: 'Egress',
		packageName: '@absolutejs/egress',
		private: false,
		repository: 'https://github.com/absolutejs/egress',
		subpackages: [],
		version: '0.2.0'
	},
	{
		category: 'Messaging',
		description:
			'Provider-neutral email sync adapters for AbsoluteJS: Gmail, Microsoft Graph, and IMAP.',
		directory: 'email',
		kind: 'package',
		name: 'Email',
		packageName: '@absolutejs/email',
		private: false,
		repository: 'https://github.com/absolutejs/email',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Monorepo root for @absolutejs/engagement sales-engagement adapters — enrichment + outreach activity from Apollo, Outreach, Salesloft, … normalized to the EngagementSource contract. Subpackages live in ./<name>/ and publish independently as @absolutejs/engagement-<name>.',
		directory: 'engagement-adapters',
		kind: 'monorepo',
		name: 'Engagement Adapters',
		packageName: 'engagement-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/engagement-adapters',
		subpackages: [
			{
				description:
					'The EngagementSource contract + normalized types for @absolutejs/engagement sales-engagement adapters — enrichment (person/company) and outreach activity (email/LinkedIn/call touchpoints).',
				name: '@absolutejs/engagement',
				private: false,
				version: '0.0.8'
			},
			{
				description:
					'Apollo.io EngagementSource adapter for @absolutejs/engagement — person/company enrichment and outreach activity (emails sent/opened/replied) from the Apollo API.',
				name: '@absolutejs/engagement-apollo',
				private: false,
				version: '0.0.8'
			}
		],
		version: null
	},
	{
		category: 'Commerce & Growth',
		description:
			"In-house B2B enrichment — MX/SMTP/catch-all email verification, decision-maker email finding, and keyless public-profile enrichment (avatars, logos, social handles), so you don't pay PDL/Apollo/Clearbit per lookup.",
		directory: 'enrich',
		kind: 'package',
		name: 'Enrich',
		packageName: '@absolutejs/enrich',
		private: false,
		repository: 'https://github.com/absolutejs/enrich',
		subpackages: [],
		version: '0.1.4'
	},
	{
		category: 'Observability',
		description:
			'Effect-native, Sentry-equivalent exception capture for the AbsoluteJS substrate. createErrorTracker decorates @absolutejs/audit + @absolutejs/telemetry + a durable issue store; capture() returns a CaptureOutcome with per-sink delivery state + typed (Data.TaggedError) failures — errors-as-values. Plus /ingest (coalescing buffer + Schema-validated endpoint + drainer for browser beacon payloads) and /symbolicate (source-map stack rewriting). No vendor lock-in.',
		directory: 'errors',
		kind: 'package',
		name: 'Errors',
		packageName: '@absolutejs/errors',
		private: false,
		repository: 'https://github.com/absolutejs/errors',
		subpackages: [],
		version: '0.7.1'
	},
	{
		category: 'Observability',
		description:
			'Monorepo root for @absolutejs/errors issue-store adapters. Subpackages live in ./<name>/ and publish independently.',
		directory: 'errors-adapters',
		kind: 'monorepo',
		name: 'Errors Adapters',
		packageName: 'errors-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/errors-adapters',
		subpackages: [
			{
				description:
					'Postgres-backed, Effect-native IssueStore for @absolutejs/errors with first-class Drizzle and tagged-template adapters.',
				name: '@absolutejs/errors-postgres',
				private: false,
				version: '0.1.3'
			}
		],
		version: null
	},
	{
		category: 'Dev Tools',
		description: 'ESLint plugin for AbsoluteJS',
		directory: 'eslint-plugin',
		kind: 'package',
		name: 'ESLint Plugin',
		packageName: 'eslint-plugin-absolute',
		private: false,
		repository: 'https://github.com/absolutejs/eslint-plugin-absolute',
		subpackages: [],
		version: '0.11.27'
	},
	{
		category: 'Dev Tools',
		description:
			'Runnable examples demonstrating AbsoluteJS framework features and ecosystem packages.',
		directory: 'examples',
		kind: 'monorepo',
		name: 'Examples',
		packageName: null,
		private: true,
		repository: 'https://github.com/absolutejs/examples',
		subpackages: [
			{
				description: 'No package description provided.',
				name: 'absolute-ai-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-auth-example',
				private: true,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-crm-example',
				private: true,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-demo-example',
				private: true,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-error-boundaries-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-image-optimization-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-island-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-isolated-jsc-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-out-of-order-streaming-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-queue-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-rag-vector-example',
				private: true,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-rate-limit-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-service-worker-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-spa-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-stylelab-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-sync-example',
				private: false,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-voice-example',
				private: true,
				version: '0.0.1'
			},
			{
				description: 'No package description provided.',
				name: 'absolutejs-web-worker-example',
				private: false,
				version: '0.0.1'
			},
			{
				description:
					'Runnable showcase for citra — authorize, callback, refresh, revoke, and fetch-profile against every supported OAuth2 provider.',
				name: 'citra-example',
				private: true,
				version: '0.0.1'
			}
		],
		version: null
	},
	{
		category: 'AI',
		description:
			'Crash-safe external effect execution for AI agents with a transactional outbox, queue integration, reconciliation, and compensation.',
		directory: 'execution',
		kind: 'package',
		name: 'Execution',
		packageName: '@absolutejs/execution',
		private: false,
		repository: 'https://github.com/absolutejs/execution',
		subpackages: [],
		version: '0.14.7'
	},
	{
		category: 'Data & Sync',
		description:
			'Provider-neutral authenticated Git source ingestion, webhook normalization, exact-revision materialization, and provenance for Bun and AbsoluteJS.',
		directory: 'git',
		kind: 'package',
		name: 'Git',
		packageName: '@absolutejs/git',
		private: false,
		repository: 'https://github.com/absolutejs/git',
		subpackages: [],
		version: '0.5.1'
	},
	{
		category: 'AI',
		description:
			'Correlation, evidence, reconciliation, and visibility primitives for work handed to external systems.',
		directory: 'handoff',
		kind: 'package',
		name: 'Handoff',
		packageName: '@absolutejs/handoff',
		private: false,
		repository: 'https://github.com/absolutejs/handoff',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Observability',
		description:
			'Liveness + readiness probes for the AbsoluteJS substrate. createHealthChecker composes named checks; healthPlugin exposes /healthz (process alive?) + /readyz (can serve traffic?) with a standard JSON envelope. Per-check timeout, aggregate worst-of-any status, Cache-Control: no-store.',
		directory: 'health',
		kind: 'package',
		name: 'Health',
		packageName: '@absolutejs/health',
		private: false,
		repository: 'https://github.com/absolutejs/health',
		subpackages: [],
		version: '0.3.0'
	},
	{
		category: 'Frontend & UX',
		description:
			'Framework-agnostic keyboard shortcuts: chords, sequences, scopes and a self-describing binding registry.',
		directory: 'hotkeys',
		kind: 'package',
		name: 'Hotkeys',
		packageName: '@absolutejs/hotkeys',
		private: false,
		repository: 'https://github.com/absolutejs/hotkeys',
		subpackages: [],
		version: '0.1.1'
	},
	{
		category: 'Observability',
		description:
			'Durable incident delivery workers with leases, retries, escalation preparation, and operator metrics.',
		directory: 'incidents',
		kind: 'package',
		name: 'Incidents',
		packageName: '@absolutejs/incidents',
		private: false,
		repository: 'https://github.com/absolutejs/incidents',
		subpackages: [],
		version: '0.1.2'
	},
	{
		category: 'Platform & Infra',
		description:
			'JavaScriptCore-native sandbox for Bun — heap-isolated execution for untrusted code, isolated-vm-shaped API',
		directory: 'isolated-jsc',
		kind: 'package',
		name: 'isolated-jsc',
		packageName: '@absolutejs/isolated-jsc',
		private: false,
		repository: 'https://github.com/absolutejs/isolated-jsc',
		subpackages: [],
		version: '0.12.4'
	},
	{
		category: 'Auth & Identity',
		description:
			'Shared linked-provider credential and resolver contracts for AbsoluteJS packages',
		directory: 'linked-providers',
		kind: 'package',
		name: 'Linked Providers',
		packageName: '@absolutejs/linked-providers',
		private: false,
		repository: 'https://github.com/absolutejs/linked-providers',
		subpackages: [],
		version: '0.0.5'
	},
	{
		category: 'Observability',
		description:
			'Structured log primitive for the AbsoluteJS substrate. Levels, child loggers, sinks (console-JSON, console-pretty, memory, rotating file), optional secret redaction via @absolutejs/secrets, optional trace-id correlation via @absolutejs/telemetry. Metrics surface for @absolutejs/metrics.',
		directory: 'logs',
		kind: 'package',
		name: 'Logs',
		packageName: '@absolutejs/logs',
		private: false,
		repository: 'https://github.com/absolutejs/logs',
		subpackages: [],
		version: '0.2.1'
	},
	{
		category: 'AI',
		description:
			'The AbsoluteJS package manifest contract. Every @absolutejs/* package exports a typed manifest (settings schema, env requirements, adapter slots, wiring recipes, AI tools) from its ./manifest subpath; this package is the contract those manifests are written against, plus bridges that turn any manifest into an AI tool map or a remote MCP tool registry.',
		directory: 'manifest',
		kind: 'package',
		name: 'Manifest',
		packageName: '@absolutejs/manifest',
		private: false,
		repository: 'https://github.com/absolutejs/manifest',
		subpackages: [],
		version: '0.8.0'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Provider-agnostic marketplace primitives for listings, criteria orders, auctions, trades, and atomic collectible settlement.',
		directory: 'marketplace',
		kind: 'package',
		name: 'Marketplace',
		packageName: '@absolutejs/marketplace',
		private: false,
		repository: 'https://github.com/absolutejs/marketplace',
		subpackages: [],
		version: '0.1.7'
	},
	{
		category: 'AI',
		description:
			'Serve a remote Model Context Protocol endpoint (streamable HTTP, stateless) from a tool/prompt/resource registry — OAuth bearer auth, RFC 9728 discovery, and per-call guards are yours to wire, the JSON-RPC protocol is done correctly by construction.',
		directory: 'mcp',
		kind: 'package',
		name: 'Mcp',
		packageName: '@absolutejs/mcp',
		private: false,
		repository: 'https://github.com/absolutejs/mcp',
		subpackages: [],
		version: '0.11.3'
	},
	{
		category: 'Voice & Media',
		description: 'Realtime media primitives for AbsoluteJS',
		directory: 'media',
		kind: 'package',
		name: 'Media',
		packageName: '@absolutejs/media',
		private: false,
		repository: 'https://github.com/absolutejs/media',
		subpackages: [],
		version: '0.0.1-beta.24'
	},
	{
		category: 'Voice & Media',
		description:
			'Meeting-bot core for AbsoluteJS — join a call (via a source adapter), transcribe it live with the voice scribe, and surface diarized turns + participants for analysis',
		directory: 'meeting',
		kind: 'package',
		name: 'Meeting',
		packageName: '@absolutejs/meeting',
		private: false,
		repository: 'https://github.com/absolutejs/meeting',
		subpackages: [],
		version: '0.0.1-beta.11'
	},
	{
		category: 'Voice & Media',
		description:
			'Voice-source adapters that connect meeting platforms to @absolutejs/meeting.',
		directory: 'meeting-adapters',
		kind: 'monorepo',
		name: 'Meeting Adapters',
		packageName: null,
		private: true,
		repository: 'https://github.com/absolutejs/meeting-adapters',
		subpackages: [
			{
				description:
					'Discord voice source adapter for @absolutejs/meeting — a bot joins a Discord voice channel and streams per-participant audio (speakers known, no diarization needed) into the meeting core for live transcription + analysis',
				name: '@absolutejs/meeting-discord',
				private: false,
				version: '0.0.1-beta.17'
			},
			{
				description:
					'Recall.ai source adapter for @absolutejs/meeting — Recall joins a Google Meet / Zoom / Teams call as a bot and streams per-participant audio into the meeting core for live transcription + analysis',
				name: '@absolutejs/meeting-recall',
				private: false,
				version: '0.0.1-beta.10'
			}
		],
		version: null
	},
	{
		category: 'Platform & Infra',
		description:
			'Per-tenant cost-attribution + budget enforcement for multi-tenant runtimes. Consumes handlerMetrics from @absolutejs/sync and spawn/idle/exit events from @absolutejs/runtime; rolls up CPU-ms, bytes egress, hibernation-GB-seconds per tenant; trips a circuit breaker when a per-tenant budget is exceeded.',
		directory: 'metering',
		kind: 'package',
		name: 'Metering',
		packageName: '@absolutejs/metering',
		private: false,
		repository: 'https://github.com/absolutejs/metering',
		subpackages: [],
		version: '0.6.0'
	},
	{
		category: 'Observability',
		description:
			"Prometheus / OpenMetrics exposure for the AbsoluteJS substrate. Standardizes every package's metrics() shape into MetricSample[] + a Prometheus text-format renderer + an Elysia metricsPlugin. Per-source collectors as subpaths: runtime, router, egress, queue, sync, secrets, rate-limit, audit, dispatch, errors, logs.",
		directory: 'metrics',
		kind: 'package',
		name: 'Metrics',
		packageName: '@absolutejs/metrics',
		private: false,
		repository: 'https://github.com/absolutejs/metrics',
		subpackages: [],
		version: '0.3.2'
	},
	{
		category: 'Observability',
		description:
			'Managed AbsoluteJS observability: correlated browser and server errors plus privacy-masked Replay through a credential-safe Elysia relay.',
		directory: 'observability',
		kind: 'package',
		name: 'Observability',
		packageName: '@absolutejs/observability',
		private: false,
		repository: 'https://github.com/absolutejs/observability',
		subpackages: [],
		version: '0.4.3'
	},
	{
		category: 'On-chain',
		description:
			'Gasless collectible provenance for AbsoluteJS apps: attested minting, literal editions, immutable origin ownership, and marketplace-controlled transfers.',
		directory: 'onchain',
		kind: 'package',
		name: 'Onchain',
		packageName: '@absolutejs/onchain',
		private: false,
		repository: 'https://github.com/absolutejs/onchain',
		subpackages: [],
		version: '0.1.2'
	},
	{
		category: 'On-chain',
		description:
			'Real-chain adapters for @absolutejs/onchain (the core ships a local adapter for dev/off-chain).',
		directory: 'onchain-adapters',
		kind: 'monorepo',
		name: 'On-chain Adapters',
		packageName: '@absolutejs/onchain-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/onchain-adapters',
		subpackages: [
			{
				description:
					'Base (L2) adapter for @absolutejs/onchain: gasless soulbound seed-is-asset minting, with un-forgeable, GitHub-verified attestations.',
				name: '@absolutejs/onchain-base',
				private: false,
				version: '0.0.3'
			}
		],
		version: null
	},
	{
		category: 'AI',
		description:
			"Outcome feedback loop for AI agents — typed artifact features + attribution-joined outcome stats + evidence rendering, so an agent's context (not its weights) gets measurably better per user. Experiment variants bolt on.",
		directory: 'outcomes',
		kind: 'package',
		name: 'Outcomes',
		packageName: '@absolutejs/outcomes',
		private: false,
		repository: 'https://github.com/absolutejs/outcomes',
		subpackages: [],
		version: '0.2.4'
	},
	{
		category: 'Commerce & Growth',
		description:
			"In-house partnership & relationship intelligence — AI reasoning over the full partnership lifecycle (trust & fit scoring, relationship classification, connection framing, partner verification, outreach, deal structure), provider-injected so you don't pay a deal-copilot SaaS per seat.",
		directory: 'partnership',
		kind: 'package',
		name: 'Partnership',
		packageName: '@absolutejs/partnership',
		private: false,
		repository: 'https://github.com/absolutejs/partnership',
		subpackages: [],
		version: '0.0.11'
	},
	{
		category: 'AI',
		description:
			'Versioned provider-neutral policy lifecycle, simulation, and AuthZEN adapter for AI agent actions.',
		directory: 'policy',
		kind: 'package',
		name: 'Policy',
		packageName: '@absolutejs/policy',
		private: false,
		repository: 'https://github.com/absolutejs/policy',
		subpackages: [],
		version: '0.3.1'
	},
	{
		category: 'Frontend & UX',
		description:
			'Framework-agnostic PWA + Web Push primitives — web app manifest, push service worker, VAPID sender, and browser subscription glue',
		directory: 'pwa',
		kind: 'package',
		name: 'Pwa',
		packageName: '@absolutejs/pwa',
		private: false,
		repository: 'https://github.com/absolutejs/pwa',
		subpackages: [],
		version: '0.7.2'
	},
	{
		category: 'Data & Sync',
		description:
			'A durable, typed job queue for Elysia and the AbsoluteJS ecosystem',
		directory: 'queue',
		kind: 'package',
		name: 'Queue',
		packageName: '@absolutejs/queue',
		private: false,
		repository: 'https://github.com/absolutejs/queue',
		subpackages: [],
		version: '0.7.1'
	},
	{
		category: 'Data & Sync',
		description:
			'Storage adapters for @absolutejs/queue (Postgres, Redis, and more to come)',
		directory: 'queue-adapters',
		kind: 'monorepo',
		name: 'Queue Adapters',
		packageName: '@absolutejs/queue-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/queue-adapters',
		subpackages: [
			{
				description:
					'Postgres (Drizzle) storage adapter for @absolutejs/queue — postgres.js + Neon serverless',
				name: '@absolutejs/queue-postgres',
				private: false,
				version: '0.1.4'
			},
			{
				description:
					'Redis-backed JobStore for @absolutejs/queue. Atomic Lua claim, sorted-set scheduling by runAt, per-job hash records. For shops running Redis instead of (or alongside) Postgres.',
				name: '@absolutejs/queue-redis',
				private: false,
				version: '0.0.3'
			}
		],
		version: null
	},
	{
		category: 'AI',
		description:
			'Standalone RAG ingestion, sync, retrieval, evaluation, clients, and framework adapters extracted from AbsoluteJS',
		directory: 'rag',
		kind: 'package',
		name: 'Rag',
		packageName: '@absolutejs/rag',
		private: false,
		repository: 'https://github.com/absolutejs/rag',
		subpackages: [],
		version: '0.6.2'
	},
	{
		category: 'AI',
		description:
			'Vector-store adapters for @absolutejs/rag (Pinecone, PostgreSQL/pgvector, SQLite)',
		directory: 'rag-adapters',
		kind: 'monorepo',
		name: 'RAG Adapters',
		packageName: '@absolutejs/rag-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/rag-adapters',
		subpackages: [
			{
				description:
					'Pinecone vector-store adapter for @absolutejs/rag',
				name: '@absolutejs/rag-pinecone',
				private: false,
				version: '0.0.13'
			},
			{
				description:
					'PostgreSQL (pgvector) vector-store adapter for @absolutejs/rag',
				name: '@absolutejs/rag-postgres',
				private: false,
				version: '0.0.12'
			},
			{
				description:
					'SQLite vector-store adapter for @absolutejs/rag with optional native vec0 acceleration',
				name: '@absolutejs/rag-sqlite',
				private: false,
				version: '0.0.12'
			}
		],
		version: null
	},
	{
		category: 'Platform & Infra',
		description:
			'First-class 2026 rate limit for Bun + Elysia. GCRA by default (exact, O(1) memory per key, no boundary effect — the algorithm Stripe uses), IETF draft-09 RateLimit-* headers, IPv6 /64 grouping, X-Forwarded-For trust modes, BigInt nanosecond TAT, pluggable store (memory LRU bundled).',
		directory: 'rate-limit',
		kind: 'package',
		name: 'Rate Limit',
		packageName: '@absolutejs/rate-limit',
		private: false,
		repository: 'https://github.com/absolutejs/rate-limit',
		subpackages: [],
		version: '0.5.1'
	},
	{
		category: 'Platform & Infra',
		description:
			'Provider-neutral atomic inbox, transaction, and idempotent-operation primitives for AbsoluteJS.',
		directory: 'reliability',
		kind: 'package',
		name: 'Reliability',
		packageName: '@absolutejs/reliability',
		private: false,
		repository: 'https://github.com/absolutejs/reliability',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Dev Tools',
		description:
			'Renown — earn XP and renown for real, meritorious dev work. Editor-agnostic, with 10k achievements and competitive per-project leaderboards. By AbsoluteJS.',
		directory: 'renown',
		kind: 'package',
		name: 'Renown',
		packageName: '@absolutejs/renown',
		private: false,
		repository: 'https://github.com/absolutejs/renown',
		subpackages: [],
		version: '0.3.5'
	},
	{
		category: 'Dev Tools',
		description:
			'Earn renown for real dev work — a live status bar + activity-driven sync, right in your editor. Talks to your renown server.',
		directory: 'renown-vscode-extension',
		kind: 'package',
		name: 'Renown VS Code Extension',
		packageName: 'renown-vscode',
		private: true,
		repository: 'https://github.com/absolutejs/renown-vscode-extension',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Observability',
		description:
			'Session replay for the AbsoluteJS observability stack. A tiny zero-hard-dependency recorder (rrweb is an optional, lazy-loaded peer) that chunks DOM recordings and uploads them via a pluggable transport (@absolutejs/blob), privacy-masking by default. Plus chunk assembly + a framework-agnostic player. Stamps a replayId for @absolutejs/beacon to cross-link errors to the exact session.',
		directory: 'replay',
		kind: 'package',
		name: 'Replay',
		packageName: '@absolutejs/replay',
		private: false,
		repository: 'https://github.com/absolutejs/replay',
		subpackages: [],
		version: '0.3.1'
	},
	{
		category: 'Platform & Infra',
		description:
			'Multi-tenant connection routing primitive for Bun PaaS gateways. Consistent-hash tenant→shard, per-tenant connection cap, per-tenant rate limit, healthy-shard skip. The library that goes in front of N @absolutejs/runtime instances.',
		directory: 'router',
		kind: 'package',
		name: 'Router',
		packageName: '@absolutejs/router',
		private: false,
		repository: 'https://github.com/absolutejs/router',
		subpackages: [],
		version: '0.5.2'
	},
	{
		category: 'AI',
		description:
			'Typed standing automations ("if X do Y") for AI-agent products — a closed trigger/action vocabulary drives the validator, LLM tool schemas, and a capped, cooldown-guarded firing engine, so the agent itself can author rules without hallucinating behavior.',
		directory: 'rules',
		kind: 'package',
		name: 'Rules',
		packageName: '@absolutejs/rules',
		private: false,
		repository: 'https://github.com/absolutejs/rules',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Platform & Infra',
		description:
			'Multi-tenant Bun runtime substrate for PaaS providers — spawn isolated child Bun processes per tenant, idle-kill, metric emit. The library SB-6 surfaces between isolated-jsc + sync and the hosted product downstream.',
		directory: 'runtime',
		kind: 'package',
		name: 'Runtime',
		packageName: '@absolutejs/runtime',
		private: false,
		repository: 'https://github.com/absolutejs/runtime',
		subpackages: [],
		version: '0.6.1'
	},
	{
		category: 'Frontend & UX',
		description:
			'A state management library for Elysia, scoped to individual users.',
		directory: 'scoped-state',
		kind: 'package',
		name: 'Scoped State',
		packageName: '@absolutejs/scoped-state',
		private: false,
		repository: 'https://github.com/absolutejs/scoped-state',
		subpackages: [],
		version: '0.1.4'
	},
	{
		category: 'Dev Tools',
		description:
			'Internal AbsoluteJS scripts and dev utilities (e.g. Drizzle schema → DBML generation). Not a published package.',
		directory: 'scripts',
		kind: 'package',
		name: 'Scripts',
		packageName: '@absolutejs/scripts',
		private: true,
		repository: 'https://github.com/absolutejs/scripts',
		subpackages: [],
		version: '0.0.1'
	},
	{
		category: 'Platform & Infra',
		description:
			'Host-side secret broker for multi-tenant Bun runtimes. Pluggable adapters (env-var, in-memory, composite, encrypted-file); audit hook per resolve; safe fingerprints for logs; redact() walks known secrets out of arbitrary text before it lands in a log sink.',
		directory: 'secrets',
		kind: 'package',
		name: 'Secrets',
		packageName: '@absolutejs/secrets',
		private: false,
		repository: 'https://github.com/absolutejs/secrets',
		subpackages: [],
		version: '0.9.6'
	},
	{
		category: 'Platform & Infra',
		description:
			'Storage-neutral SLO, error-budget, burn-rate, release-gate, and incident-decision primitives for AbsoluteJS.',
		directory: 'slo',
		kind: 'package',
		name: 'Slo',
		packageName: '@absolutejs/slo',
		private: false,
		repository: 'https://github.com/absolutejs/slo',
		subpackages: [],
		version: '0.1.0'
	},
	{
		category: 'Data & Sync',
		description:
			'Lightweight reactive-push and write-behind-cache primitives for Elysia and the AbsoluteJS ecosystem — kill polling and keep a remote store off your hot path, without adopting a whole sync-engine backend.',
		directory: 'sync',
		kind: 'package',
		name: 'Sync',
		packageName: '@absolutejs/sync',
		private: false,
		repository: 'https://github.com/absolutejs/sync',
		subpackages: [],
		version: '2.13.0'
	},
	{
		category: 'Data & Sync',
		description:
			'Cluster bus + CRDT backend adapters for @absolutejs/sync (PG-NOTIFY bus, Yjs, Automerge, Loro)',
		directory: 'sync-adapters',
		kind: 'monorepo',
		name: 'Sync Adapters',
		packageName: '@absolutejs/sync-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/sync-adapters',
		subpackages: [
			{
				description:
					'Automerge-backed collaborative-text CRDT adapter for @absolutejs/sync',
				name: '@absolutejs/sync-automerge',
				private: false,
				version: '0.0.4'
			},
			{
				description:
					'Typed Postgres LISTEN/NOTIFY channel and @absolutejs/sync cluster bus — horizontal scale without standing up Redis',
				name: '@absolutejs/sync-bus-pg',
				private: false,
				version: '0.2.3'
			},
			{
				description:
					'Redis pub/sub ClusterBus for @absolutejs/sync — cross-instance fan-out via PUBLISH/SUBSCRIBE. Sibling to @absolutejs/sync-bus-pg; faster fanout, better geo-replication story. Works with any Redis client (ioredis, node-redis, etc.) via a narrow tag-template interface.',
				name: '@absolutejs/sync-bus-redis',
				private: false,
				version: '0.1.1'
			},
			{
				description:
					'Loro-backed collaborative-text CRDT adapter for @absolutejs/sync',
				name: '@absolutejs/sync-loro',
				private: false,
				version: '0.0.4'
			},
			{
				description:
					'Yjs-backed collaborative-text CRDT adapter for @absolutejs/sync',
				name: '@absolutejs/sync-yjs',
				private: false,
				version: '0.1.0'
			}
		],
		version: null
	},
	{
		category: 'Data & Sync',
		description:
			'Feature packs for @absolutejs/sync — Convex Components without the lock-in (presence, comments, scheduled-digest, ...)',
		directory: 'sync-packs',
		kind: 'monorepo',
		name: 'Sync Packs',
		packageName: '@absolutejs/sync-packs',
		private: true,
		repository: 'https://github.com/absolutejs/sync-packs',
		subpackages: [
			{
				description:
					'Threaded comments pack for @absolutejs/sync — per-resource ACL-scoped, author/moderator gates, optional CRDT bodies',
				name: '@absolutejs/sync-pack-comments',
				private: false,
				version: '0.4.5'
			},
			{
				description:
					'Read-set-tracked live counters for @absolutejs/sync — define a compute function, get a reactive count derived from host tables',
				name: '@absolutejs/sync-pack-counters',
				private: false,
				version: '0.1.5'
			},
			{
				description:
					'Scheduled per-actor digest pack for @absolutejs/sync — cron-fired, cursor-managed, transport-agnostic',
				name: '@absolutejs/sync-pack-digest',
				private: false,
				version: '0.2.5'
			},
			{
				description:
					'Per-actor saved-resources pack for @absolutejs/sync — favorite/unfavorite/pin/list with optional join to host resources',
				name: '@absolutejs/sync-pack-favorites',
				private: false,
				version: '0.2.4'
			},
			{
				description:
					'@mention parser pack for @absolutejs/sync — extracts @usernames from a body, writes per-actor mention rows, fires an onMention hook that composes with the notifications pack',
				name: '@absolutejs/sync-pack-mentions',
				private: false,
				version: '0.1.4'
			},
			{
				description:
					'Per-actor inbox pack for @absolutejs/sync — notify, mark-read, scoped reads, optional TTL auto-archive',
				name: '@absolutejs/sync-pack-notifications',
				private: false,
				version: '0.2.4'
			},
			{
				description:
					'Per-channel live presence pack for @absolutejs/sync — heartbeat-driven, scoped, TTL-cleaned, with cursor + typing state patches',
				name: '@absolutejs/sync-pack-presence',
				private: false,
				version: '0.4.3'
			},
			{
				description:
					'Per-actor triage pack for @absolutejs/sync — unread/seen, snooze that resurfaces on new activity, dismiss that sticks, and mute, over any host resource',
				name: '@absolutejs/sync-pack-triage',
				private: false,
				version: '0.1.0'
			},
			{
				description:
					'Shared helpers for @absolutejs/sync packs — resolveActor, requireRowOwner/Moderator, createInMemoryStore, and other patterns extracted from the official packs',
				name: '@absolutejs/sync-pack-utils',
				private: false,
				version: '0.1.3'
			}
		],
		version: null
	},
	{
		category: 'Observability',
		description:
			"Tiny shared OpenTelemetry substrate for the AbsoluteJS ecosystem. Type-replicates @opentelemetry/api's Tracer/Span shape, ships noop implementations + a tracerOrNoop helper + a zero-dep OTLP-HTTP-JSON span exporter (/otlp-http subpath), and pins ABS_ATTRS semantic conventions so spans from runtime / sync / queue / router / secrets all use the same attribute names.",
		directory: 'telemetry',
		kind: 'package',
		name: 'Telemetry',
		packageName: '@absolutejs/telemetry',
		private: false,
		repository: 'https://github.com/absolutejs/telemetry',
		subpackages: [],
		version: '0.2.1'
	},
	{
		category: 'Frontend & UX',
		description:
			'Element-level, cross-page product tour engine for AbsoluteJS apps. A serializable step protocol plus a spotlight positioning engine (pixel-accurate, follows late layout shifts) and a sessionStorage-backed controller that resumes across full-page navigations. Vue + vue-router are peer dependencies.',
		directory: 'tour',
		kind: 'package',
		name: 'Tour',
		packageName: '@absolutejs/tour',
		private: false,
		repository: 'https://github.com/absolutejs/tour',
		subpackages: [],
		version: '0.3.0-beta.6'
	},
	{
		category: 'Voice & Media',
		description: 'Voice primitives and Elysia plugin for AbsoluteJS',
		directory: 'voice',
		kind: 'package',
		name: 'Voice',
		packageName: '@absolutejs/voice',
		private: false,
		repository: 'https://github.com/absolutejs/voice',
		subpackages: [],
		version: '0.0.22-beta.665'
	},
	{
		category: 'Voice & Media',
		description:
			'Speech-to-text, text-to-speech, and realtime provider adapters for @absolutejs/voice.',
		directory: 'voice-adapters',
		kind: 'monorepo',
		name: 'Voice Adapters',
		packageName: '@absolutejs/voice-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/voice-adapters',
		subpackages: [
			{
				description:
					'AssemblyAI speech-to-text adapter for @absolutejs/voice',
				name: '@absolutejs/voice-assemblyai',
				private: false,
				version: '0.0.19-beta.127'
			},
			{
				description:
					'Azure Speech (Cognitive Services) adapter for @absolutejs/voice — Neural TTS over REST + streaming STT over the WebSocket Unified Speech Protocol',
				name: '@absolutejs/voice-azure',
				private: false,
				version: '0.0.1-beta.7'
			},
			{
				description:
					'Cartesia text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-cartesia',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description:
					'Deepgram speech-to-text adapter for @absolutejs/voice',
				name: '@absolutejs/voice-deepgram',
				private: false,
				version: '0.0.20-beta.104'
			},
			{
				description:
					'ElevenLabs text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-elevenlabs',
				private: false,
				version: '0.0.26'
			},
			{
				description:
					'Gemini Live realtime adapter for @absolutejs/voice',
				name: '@absolutejs/voice-gemini',
				private: false,
				version: '0.0.1-beta.44'
			},
			{
				description:
					'Gladia real-time speech-to-text adapter for @absolutejs/voice',
				name: '@absolutejs/voice-gladia',
				private: false,
				version: '0.0.1-beta.5'
			},
			{
				description:
					'Google Cloud Speech-to-Text adapter for @absolutejs/voice — buffered-batch (REST) + real-time streaming (gRPC-Web over HTTP/2, no @grpc/grpc-js dep)',
				name: '@absolutejs/voice-google-speech',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description:
					'LMNT text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-lmnt',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description:
					'Neets text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-neets',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description: 'OpenAI realtime adapter for @absolutejs/voice',
				name: '@absolutejs/voice-openai',
				private: false,
				version: '0.0.7-beta.45'
			},
			{
				description:
					'OpenAI Whisper buffered-batch speech-to-text adapter for @absolutejs/voice',
				name: '@absolutejs/voice-openai-whisper',
				private: false,
				version: '0.0.1-beta.5'
			},
			{
				description:
					'PlayHT text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-playht',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description:
					'Rime text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-rime',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description:
					'Smallest AI text-to-speech adapter for @absolutejs/voice',
				name: '@absolutejs/voice-smallest',
				private: false,
				version: '0.0.1-beta.6'
			},
			{
				description:
					'Soniox real-time speech-to-text adapter for @absolutejs/voice',
				name: '@absolutejs/voice-soniox',
				private: false,
				version: '0.0.1-beta.5'
			},
			{
				description:
					'Speechmatics real-time speech-to-text adapter for @absolutejs/voice',
				name: '@absolutejs/voice-speechmatics',
				private: false,
				version: '0.0.1-beta.5'
			}
		],
		version: null
	},
	{
		category: 'Voice & Media',
		description:
			'Multilingual audio fixtures used to evaluate and regression-test voice providers.',
		directory: 'voice-fixtures-multilingual',
		kind: 'repository',
		name: 'Multilingual Voice Fixtures',
		packageName: null,
		private: true,
		repository: null,
		subpackages: [],
		version: null
	},
	{
		category: 'Voice & Media',
		description:
			'AI-driven automated tester for @absolutejs/voice services — simulates a caller end-to-end (Twilio Media Stream protocol or real Twilio outbound), drives the conversation with TTS + STT + LLM. Built for the hosted AbsoluteJS.ai Studio.',
		directory: 'voice-tester',
		kind: 'package',
		name: 'Voice Tester',
		packageName: '@absolutejs/voice-tester',
		private: false,
		repository: 'https://github.com/absolutejs/voice-tester',
		subpackages: [],
		version: '0.0.4-beta.5'
	},
	{
		category: 'Frontend & UX',
		description:
			'A few small, broadly-useful Vue composables for AbsoluteJS apps: useHydrated (SSR hydration gate), isBrowser, useDebouncedAction, and runAsyncAction (try/catch/loading/notify wrapper with an injectable notifier). Vue is a peer dependency.',
		directory: 'vue-composables',
		kind: 'package',
		name: 'Vue Composables',
		packageName: '@absolutejs/vue-composables',
		private: false,
		repository: 'https://github.com/absolutejs/vue-composables',
		subpackages: [],
		version: '0.3.1'
	},
	{
		category: 'Platform & Infra',
		description:
			'Scanner-neutral vulnerability normalization, policy gates, host inventory, and audit-ready evidence for AbsoluteJS applications.',
		directory: 'vulnerabilities',
		kind: 'package',
		name: 'Vulnerabilities',
		packageName: '@absolutejs/vulnerabilities',
		private: false,
		repository: 'https://github.com/absolutejs/vulnerabilities',
		subpackages: [],
		version: '0.14.1'
	},
	{
		category: 'Platform & Infra',
		description:
			'Feed and storage adapters for @absolutejs/vulnerabilities.',
		directory: 'vulnerabilities-adapters',
		kind: 'monorepo',
		name: 'Vulnerability Adapters',
		packageName: '@absolutejs/vulnerabilities-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/vulnerabilities-adapters',
		subpackages: [
			{
				description:
					'FIRST EPSS probability and percentile ingestion for AbsoluteJS vulnerability prioritization.',
				name: '@absolutejs/vulnerabilities-epss',
				private: false,
				version: '0.1.6'
			},
			{
				description:
					'CISA Known Exploited Vulnerabilities catalog ingestion for AbsoluteJS.',
				name: '@absolutejs/vulnerabilities-kev',
				private: false,
				version: '0.1.6'
			},
			{
				description:
					'Official OSV API ingestion and advisory normalization for AbsoluteJS vulnerability management.',
				name: '@absolutejs/vulnerabilities-osv',
				private: false,
				version: '0.1.8'
			},
			{
				description:
					'Durable Postgres feeds, findings, alert incidents, policy history, delivery queues, remediation evidence, and risk assessments for AbsoluteJS vulnerability management.',
				name: '@absolutejs/vulnerabilities-postgres',
				private: false,
				version: '0.9.3'
			},
			{
				description:
					'Canonical Ubuntu OSV advisory ingestion for AbsoluteJS vulnerability management.',
				name: '@absolutejs/vulnerabilities-ubuntu',
				private: false,
				version: '0.1.5'
			}
		],
		version: null
	},
	{
		category: 'Platform & Infra',
		description:
			'Optional first-party modules for AbsoluteJS vulnerability management.',
		directory: 'vulnerabilities-modules',
		kind: 'monorepo',
		name: 'Vulnerability Modules',
		packageName: '@absolutejs/vulnerabilities-modules',
		private: true,
		repository: 'https://github.com/absolutejs/vulnerabilities-modules',
		subpackages: [
			{
				description:
					'Deterministic, evidence-backed, print-ready HTML reports for AbsoluteJS vulnerability management.',
				name: '@absolutejs/vulnerabilities-report',
				private: false,
				version: '0.1.2'
			},
			{
				description:
					'Independent durable transparency witness with rollback, equivocation, key-rotation, and HTTP service primitives for AbsoluteJS vulnerability evidence.',
				name: '@absolutejs/vulnerabilities-witness',
				private: false,
				version: '0.4.4'
			},
			{
				description:
					'Continuous feed refresh, inventory correlation, VEX, risk, remediation, leases, health, and metrics for AbsoluteJS vulnerability management.',
				name: '@absolutejs/vulnerabilities-worker',
				private: false,
				version: '0.2.4'
			}
		],
		version: null
	},
	{
		category: 'Commerce & Growth',
		description:
			'Provider-agnostic, double-entry dollar wallets with reservations, idempotent settlement, and closed-loop marketplace policy for AbsoluteJS apps.',
		directory: 'wallet',
		kind: 'package',
		name: 'Wallet',
		packageName: '@absolutejs/wallet',
		private: false,
		repository: 'https://github.com/absolutejs/wallet',
		subpackages: [],
		version: '0.9.3'
	},
	{
		category: 'Commerce & Growth',
		description:
			'Funding and payment-provider adapters for @absolutejs/wallet.',
		directory: 'wallet-adapters',
		kind: 'monorepo',
		name: 'Wallet Adapters',
		packageName: '@absolutejs/wallet-adapters',
		private: true,
		repository: 'https://github.com/absolutejs/wallet-adapters',
		subpackages: [
			{
				description:
					'Stripe Checkout funding, verified webhook normalization, refunds, and dispute actions for @absolutejs/wallet.',
				name: '@absolutejs/wallet-stripe',
				private: false,
				version: '0.4.4'
			}
		],
		version: null
	},
	{
		category: 'AI',
		description:
			'Secure WebMCP registration, policy, audit, and test adapters for browser-native AI agent actions.',
		directory: 'webmcp',
		kind: 'package',
		name: 'WebMCP',
		packageName: '@absolutejs/webmcp',
		private: false,
		repository: 'https://github.com/absolutejs/webmcp',
		subpackages: [],
		version: '0.1.5'
	}
];
